---
abstract: 'processing a queue in parallel'
author:
  - 'Markus Benning <me@w3r3wolf.de>'
build_requires:
  Test: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IPC-QWorker
requires:
  Carp: 0
  Data::Dumper: 0
  IO::Select: 0
  IO::Socket: 0
  Storable: 0
  perl: 5.000
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=IPC-QWorker
  repository: https://github.com/benningm/IPC-QWorker
version: 0.07
